name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run bootstrap
        npm run build
        npm run ui:build
        npm run test -- --forceExit
      env:
        CI: true
        HEADLESS: false
        PROGRESS: none

